# Generated by Django 4.2.7 on 2024-03-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Periodicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vars",
                    models.CharField(
                        max_length=50, verbose_name="Variants of periodicity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant",
                "verbose_name_plural": "Variants",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Name mailing",
                    ),
                ),
                (
                    "data_mailing",
                    models.DateTimeField(verbose_name="Datetime of mailing"),
                ),
                (
                    "data_mailing_finish",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Finish datetime of mailing (optional)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Status mailing",
                    ),
                ),
                (
                    "periodicity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.periodicity",
                        verbose_name="periodicity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailing",
                "verbose_name_plural": "Mailings",
            },
        ),
    ]
