# Generated by Django 4.2.7 on 2024-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("lastname", models.CharField(max_length=50, verbose_name="Lastname")),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Comment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
