# Generated by Django 4.2.7 on 2024-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datatime", models.DateTimeField(verbose_name="Datatime")),
                ("status", models.CharField(max_length=150, verbose_name="Status")),
                (
                    "answer_mail_server",
                    models.TextField(verbose_name="Answer of mailserver"),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
    ]
